apiVersion: email.cloudflare.m.cloudflare.com/v1alpha1
kind: EmailRoutingSettings
metadata:
  annotations:
    meta.upbound.io/example-id: email/v1alpha1/emailroutingsettings
  labels:
    testing.upbound.io/example-name: example_email_routing_settings
  name: example-email-routing-settings
  namespace: crossplane-system
spec:
  forProvider:
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
