apiVersion: misc.cloudflare.m.cloudflare.com/v1alpha1
kind: HyperdriveConfig
metadata:
  annotations:
    meta.upbound.io/example-id: misc/v1alpha1/hyperdriveconfig
  labels:
    testing.upbound.io/example-name: example_hyperdrive_config
  name: example-hyperdrive-config
  namespace: crossplane-system
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    caching:
      disabled: true
    mtls:
      caCertificateId: 00000000-0000-0000-0000-0000000000
      mtlsCertificateId: 00000000-0000-0000-0000-0000000000
      sslmode: verify-full
    origin:
      database: postgres
      host: database.example.com
      passwordSecretRef:
        key: example-key
        name: example-secret
      port: 5432
      scheme: postgres
      user: postgres
    originConnectionLimit: 60
