apiVersion: waitingroom.cloudflare.m.cloudflare.com/v1alpha1
kind: WaitingRoomSettings
metadata:
  annotations:
    meta.upbound.io/example-id: waitingroom/v1alpha1/waitingroomsettings
  labels:
    testing.upbound.io/example-name: example_waiting_room_settings
  name: example-waiting-room-settings
  namespace: crossplane-system
spec:
  forProvider:
    searchEngineCrawlerBypass: true
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
