apiVersion: apishield.cloudflare.crossplane.io/v1alpha1
kind: APIShieldOperationSchemaValidationSettings
metadata:
  annotations:
    meta.upbound.io/example-id: apishield/v1alpha1/apishieldoperationschemavalidationsettings
  labels:
    testing.upbound.io/example-name: example_api_shield_operation_schema_validation_settings
  name: example-api-shield-operation-schema-validation-settings
spec:
  forProvider:
    mitigationAction: block
    operationId: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
